#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100.
#+ Displays FizzBuzz when the number is a multiple of 3 and 5
#+ Displays Fizz when the number is multiple of 3
#+ Displays Buzz when the number is a multiple of 5
#+ Otherwise, displays the number
#+ In a list format

start=1
stop=100

while [ "$start" -le "$stop" ]; do
	if (( start % 3 == 0 )); then
		echo "Fizz"
	elif ((start % 5 == 0)); then
		echo "Buzz"
	elif ((start % 3 == 0 && start % 5 == 0)); then
		echo "FizzBuzz"
	else
		echo "$start"
	fi

	((start++))
done
