#!/bin/bash
# Bash script that groups visitors by IP and HTTP status code,
#+ and displays this data.

LOG_FILE="/var/log/apache/access.log"

awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' "$LOG_FILE" | sort -nr
