#!/usr/bin/env bash
# A bash script that displays 'Best School' 10 times,
#+ but for the 9th iteration,
#+ `Best School` and `Hi` on a new line

start=1
stop=10
while [ "$start" -le "$stop" ]; do
	if [ "$start" -eq 9 ]; then
		echo "Best School"
		echo "Hi"
		((start++))
	else
		echo "Best School"
		((start++))
	fi
done
