#!/usr/bin/env bash
# Write a Bash script that displays the time
#+ for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

hours=0
hoursLimit=12
minutes=0
minutesLimit=60

while [ "$hours" -le "$hoursLimit" ]; do
	while [ "$minutes" -lt "$minutesLimit" ]; do
		case "$minutes" in
			0)
				echo "Hour: $hours"
				((minutes++))
				;;
			*)
				echo "$minutes"
				((minutes++))
		esac
	done
	minutes=0
	((hours++))

	case "$hours" in
		12)
			echo "Hour: $hours"
			hours=13
	esac
done
