#!/usr/bin/env bash
# A bash script that displays
#+ The content of the current directory
#+ in a list format
#+ Where only the part of the name after the first dash is displayed

for file in *; do
	if [ -f "$file" ]; then
		namefile=$(echo "$file" | cut -d'-' -f2-)
		echo "$namefile"
	fi
done
